#!/usr/bin/env bash

usage (){

echo
echo "usage: $0 -d <distro> [path]"
echo "options"
echo "  -s                 safe mode, print but does not patch"
echo "  -d   <distro>      ubuntu[1604] or Centos7"
echo "  -l   <file_path>   Were to put the list of file to patch"
echo "                       [Defautl: /tmp/list_to_patch]"
echo "  -f   <file_path>   List of libs/files to patch if not given the list"
echo "                       will be crated on on the fly from path"

}


export MUGQIC_INSTALL_HOME=/cvmfs/soft.mugqic/CentOS6
export list_to_patch=/tmp/list_to_patch
while getopts ":l:d:f:s" opt; do
  case $opt in
    s)
      export SAFE_MODE=true
      ;;
    d)
      export DISTRO=${OPTARG}
      ;;
    l)
      export list_to_patch=${OPTARG}
      ;;
    f)
      export FROM_FILE=${OPTARG}
      ;;
   h)
      usage
      exit 0
      ;;
   \?)
      usage
      exit 1
      ;;
  esac
done

shift $(($OPTIND - 1))

if [[ ! -n ${FROM_FILE} ]] && [[ ! $# == 1 ]]; then
   usage
   exit 1
fi
TO_PATCH=${1}

if [[ ${DISTRO} == [Uu]buntu ]] ; then
  echo "Ubuntu"
  export C3G_SYSTEM_LIBRARY=/cvmfs/soft.mugqic/apt/ubuntu1604/1.0
  export LIB=lib
  export INTERPRETER=$C3G_SYSTEM_LIBRARY/$LIB/x86_64-linux-gnu/ld-linux-x86-64.so.2
  export LIBDIR=$C3G_SYSTEM_LIBRARY/$LIB/x86_64-linux-gnu:$C3G_SYSTEM_LIBRARY/usr/$LIB/x86_64-linux-gnu:$C3G_SYSTEM_LIBRARY/$LIB:$C3G_SYSTEM_LIBRARY/usr/$LIB
elif [[ ${DISTRO} == [Cc]entos7 ]] || [[ ${DISTRO} == [Cc]7 ]] ; then

   export EXCLUDE_PATH="/cvmfs/soft.mugqic/yum/centos7/1.0/usr/local/c3g"
   export LIBDIR=/cvmfs/soft.mugqic/yum/centos7/1.0/usr/local/lib64:/cvmfs/soft.mugqic/yum/centos7/1.0/usr/lib64:/cvmfs/soft.mugqic/yum/centos7/1.0/usr/local/lib:/cvmfs/soft.mugqic/yum/centos7/1.0/usr/lib:/

   export INTERPRETER=/cvmfs/soft.mugqic/yum/centos7/1.0/lib64/ld-linux-x86-64.so.2
else
  echo please pick a disto for the patch
  usage
  exit 1
fi


safe_mode (){
  echo patchelf --remove-rpath ${@: -1}
  echo patchelf $@
  if [[ -n ${SAFE_MODE} ]]; then
    echo safe_mode
  else
    echo applying
    patchelf --remove-rpath ${@: -1}
    patchelf $@
  fi
}


do_patch(){
  NEW_RPATH=
  file_path=${1}
  echo "*************************************************************************"
  echo rpath ${file_path}
  readelf -d ${file_path}
  if $MUGQIC_INSTALL_HOME/software/patchelf/patchelf-0.9/bin/patchelf --print-rpath ${file_path}; then
    CURRENT_RPATH=$($MUGQIC_INSTALL_HOME/software/patchelf/patchelf-0.9/bin/patchelf --print-rpath ${file_path}):
    echo Old rpath $CURRENT_RPATH
    for current in ${CURRENT_RPATH//:/$'\n'}; do
      if [[ ${LIBDIR}  =~ .*${current}.*   ]]; then
        echo ejecting $current already in LIBDIR
        continue
      elif [[  ${EXCLUDE_PATH} =~ .*${current}.* ]]; then
        echo ejecting $current, is in EXCLUDE_PATH
        continue
      elif [[ $current =~ .*soft.mugqic.*  ]]; then
        echo ejecting $current, is cvmfs rpath but not explicitely in LIBDIR
        continue
      elif [[ ! $current =~ .*ORIGIN.*  ]]; then
        echo ejecting $current is neither cvmfs or ORIGIN
        continue
      fi
      NEW_RPATH=$current:$NEW_RPATH

    done

  else
    NEW_RPATH=""
  fi

  RPATH=${NEW_RPATH#:}${LIBDIR}
  echo New rpath ${RPATH}

if readelf -l ${file_path} | grep go.build > /dev/null; then
    echo "NOOOOO" ${file_path}
elif [[ ${file_path##*.} == "so" ]] || [[ ${file_path##*/} =~ "so"*(\.[0-9]+[a-z]*)*$ ]]; then
    echo OUI ${file_path}
safe_mode  --force-rpath --set-rpath ${RPATH} ${file_path}
else
    echo DOUBLE OUI ${file_path}
safe_mode  --set-interpreter $INTERPRETER --force-rpath --set-rpath $RPATH ${file_path}
fi
ldd ${file_path}


}


patch_from_file() {

while read file_path; do
 do_patch ${file_path}4
done < $FROM_FILE

}


patch_dir () {
  rm $list_to_patch 2>/dev/null
  TO_PATCH=$1
  echo $TO_PATCH
  find ${TO_PATCH} -type f ! -name "*.[ch]" ! -name "*.[hc]pp" ! -name "*.rd[sbaxc]" \
  ! -name "*.md" ! -name "*.html" ! -name "*.py" ! -name "*.gz" ! -name "*.tar" \
  ! -name "*.py[oc]" ! -name "*.py" ! -name "*.css" \
  ! -name "*.pl" | parallel -j 55 file   |  grep ELF \
  | grep -v "statically linked\|relocatable" | awk -F ":" '{print $1}' \
  | xargs -i bash -c "echo {} >> $list_to_patch ; do_patch {}"
}

if [[ -n ${FROM_FILE} ]] ;then
  patch_from_file
else
  patch_dir $TO_PATCH
fi
